In [1]:
from google.colab import files

uploaded = files.upload()

In [2]:
import pandas as pd
import glob

csv_files = glob.glob("*.csv")

df = pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)

print("Total rows:", len(df))
df.head()

Total rows: 252384

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,d3d413b884cd8c82a9c54e0975416f22276eee85373355...,2023-06,Cambridgeshire Constabulary,Cambridgeshire Constabulary,-0.220389,51.589997,On or near Glebe Crescent,E01000243,Barnet 032C,Violence and sexual offences,Status update unavailable,NaN
1,8dbfb834187970e08658daedc771b4012528bfff21ee80...,2023-06,Cambridgeshire Constabulary,Cambridgeshire Constabulary,-2.347641,51.357454,On or near Beechwood Road,E01014389,Bath and North East Somerset 018C,Violence and sexual offences,Investigation complete; no suspect identified,NaN
2,29d2169da151b3c12466ab2fe203907f883d6fa0d3a620...,2023-06,Cambridgeshire Constabulary,Cambridgeshire Constabulary,-0.377714,52.244713,On or near Moor Road,E01017543,Bedford 004E,Violence and sexual offences,Unable to prosecute suspect,NaN
3,NaN,2023-06,Cambridgeshire Constabulary,Cambridgeshire Constabulary,0.133124,52.228862,On or near Campkin Road,E01017975,Cambridge 001A,Anti-social behaviour,NaN,NaN
4,NaN,2023-06,Cambridgeshire Constabulary,Cambridgeshire Constabulary,0.133816,52.226808,On or near Haviland Way,E01017975,Cambridge 001A,Anti-social behaviour,NaN,NaN

In [3]:
def row_to_text(row):
    return f"""
Crime Report:
Crime ID: {row.get('Crime ID', 'Unknown')}
Date: {row.get('Month', 'Unknown')}
Reported by: {row.get('Reported by', 'Unknown')}
Area: {row.get('Falls within', 'Unknown')}
Location: {row.get('Location', 'Unknown')}
LSOA: {row.get('LSOA name', 'Unknown')}
Crime Type: {row.get('Crime type', 'Unknown')}
Outcome: {row.get('Last outcome category', 'Unknown')}
Coordinates: Latitude {row.get('Latitude', 'Unknown')}, Longitude {row.get('Longitude', 'Unknown')}
"""

In [4]:
df = df.fillna("Unknown")

df = df.drop_duplicates(subset=["Location", "Crime type", "Month"])
df = df.sample(80000, random_state=42)

In [5]:
print("Total rows:", len(df))
df.head()

Total rows: 80000

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
49851,Unknown,2025-07,Cambridgeshire Constabulary,Cambridgeshire Constabulary,0.102668,52.687024,On or near Churchill Road,E01018095,Fenland 001B,Anti-social behaviour,Unknown,Unknown
10027,e39f137d4532080c699c6aa1b318994145501a9ee4ba09...,2022-09,Cambridgeshire Constabulary,Cambridgeshire Constabulary,0.077474,52.509548,On or near Ash Tree Close,E01018111,Fenland 010C,Violence and sexual offences,Unable to prosecute suspect,Unknown
42599,a6c7ccec3747db82edf9ae453d80d96a2ebb7787988ece...,2024-01,Cambridgeshire Constabulary,Cambridgeshire Constabulary,0.142008,52.198344,On or near Mill Road,E01018001,Cambridge 009E,Shoplifting,Investigation complete; no suspect identified,Unknown
82126,544b16c4f71d4c6a9fad1ff15419f94b7ee59c8e226c77...,2022-10,Cambridgeshire Constabulary,Cambridgeshire Constabulary,-0.227395,52.589124,On or near Derby Drive,E01015653,Peterborough 012D,Burglary,Investigation complete; no suspect identified,Unknown
194051,0f55edd14bd0fc4e9bc010e99af3dda9aebdb32c973f62...,2022-12,Cambridgeshire Constabulary,Cambridgeshire Constabulary,-0.244157,52.563489,On or near Regal Place,E01015621,Peterborough 017A,Criminal damage and arson,Investigation complete; no suspect identified,Unknown

In [6]:
df["text"] = df.apply(row_to_text, axis=1)

In [7]:
df[["text"]].to_json("crime_processed_data.jsonl", orient="records", lines=True)

In [8]:

files.download("crime_processed_data.jsonl")